<?php

/**
 * @file
 * Code for the Recomended material paragraph feature.
 */

include_once 'reol_rec_material_paragraph.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function reol_rec_material_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'recommended_material') {
      $ting_entity = NULL;

      $variables['link'] = '';
      $variables['cover'] =
        $variables['author'] =
        $variables['title'] = array();

      $wrapper = $variables['paragraphs_item']->wrapper();
      $link = $wrapper->field_rec_material->value();
      $ting_entity = _reol_base_object_from_url($link);

      if ($ting_entity) {
        $ting_entity->reol_no_link = TRUE;
        $build = ting_object_view($ting_entity, 'compact');
        $uri = entity_uri('ting_object', $ting_entity);
        $variables['link'] = url($uri['path'], $uri['options']);
        $variables['cover'] = $build['ting_cover'];
        $variables['author'] = $build['ting_author'];
        $variables['title'] = $build['ting_title'];
      }
    }
  }
}
