<?php

/**
 * @file
 * Code for the Recomended material paragraph feature.
 */

include_once 'reol_rec_material_paragraph.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function reol_rec_material_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'recommended_material') {
      $ting_entity = NULL;

      $variables['cover'] =
        $variables['author'] =
        $variables['title'] = array();

      $wrapper = $variables['paragraphs_item']->wrapper();
      $link = $wrapper->field_rec_material->value();
      if (preg_match('{ting/(?:object|collection)/(.*)$}', $link, $matches)) {
        $object_id = urldecode($matches[1]);
        $ting_entity = ding_entity_load($object_id);
      }

      if ($ting_entity) {
        $ting_entity->reol_no_link = TRUE;
        $build = ting_object_view($ting_entity, 'compact');
        $variables['link'] = entity_uri('ting_entity', $ting_entity);
        $variables['cover'] = $build['ting_cover'];
        $variables['author'] = $build['ting_author'];
        $variables['title'] = $build['ting_title'];
      }
    }
  }
}
