services:
  mariadb:
    # @see https://symfony.com/doc/current/setup/symfony_server.html#docker-integration
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  node:
    image: node:16
    profiles:
      - dev
    networks:
      - app
    volumes:
      - .:/app
