<?php

/**
 * @file
 * Code for the Link paragraph feature.
 */

include_once 'reol_link_paragraph.features.inc';

/**
 * Template preprocessor for entities.
 */
function reol_link_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'linkbox') {
      $wrapper = $variables['paragraphs_item']->wrapper();
      $variables['classes_array'][] = 'linkbox';

      $color = $wrapper->field_link_color->value();
      if (isset($color['rgb'])) {
        $variables['attributes_array']['style'] = 'background-color: ' . $color['rgb'] . ';';
        // Use dark text for light color.
        if ($color['rgb'] == '#dcdcdc') {
          $variables['classes_array'][] = 'linkbox--dark-text';
        }
      }
      else {
        // Use dark text for transparent color.
        $variables['classes_array'][] = 'linkbox--dark-text';
      }

      $variables['icons'] = '';
      $link = $wrapper->field_link->value();
      if (isset($link['url'])) {
        $variables['href'] = url($link['url'], array(
          'query' => $link['query'] ?? NULL,
          'fragment' => $link['fragment'] ?? NULL,
        ));
        $variables['link_attributes'] =  drupal_attributes($link['attributes'] ?? []);

        if (!preg_match('{^' . preg_quote($GLOBALS['base_url']) . '}', $link['url'])) {
          $variables['icons'] = theme('reol_overlay_icons', array('icons' => array('link')));
        }
      }

      $image = $wrapper->field_link_gfx->value();
      if ($image['uri']) {
        $params = array(
          'style_name' => 'medium',
          'path' => $image['uri'],
        );

        $originalImage = '<img src="' . file_create_url($image['uri']) . '"/>';

        $variables['image'] = $wrapper->field_link_gfx->value()['filemime'] === 'image/gif' ? $originalImage : theme('image_style', $params);
        $variables['classes_array'][] = 'linkbox--with-image';
      }
      if (isset($link['title'])) {
        $variables['title'] = check_plain($link['title']);
      }
    }
  }
}

/**
 * Implements hook_paragraphs_item_access().
 *
 * Hide non-web link boxes from web.
 */
function reol_link_paragraph_paragraphs_item_access($entity, $op, $account) {
  if ($entity instanceof ParagraphsItemEntity
    && 'linkbox' === $entity->bundle()
    && 'view' === $op) {
    $wrapper = $entity->wrapper();
    $show_on = $wrapper->field_show_on->value();
    if (!in_array('web', $show_on, TRUE)) {
      return PARAGRAPHS_ITEM_ACCESS_DENY;
    }
  }

  return PARAGRAPHS_ITEM_ACCESS_IGNORE;
}
