<?php

/**
 * @file
 * Module for making lists of content with fancy theming.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function breol_fancy_box_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_theme().
 */
function breol_fancy_box_theme($existing, $type, $theme, $path) {
  return array(
    'breol_fancy_box' => array(
      'variables' => array(
        'nodes' => array()
      ),
      'path' => drupal_get_path('module', 'breol_fancy_box') . '/templates',
      'template' => 'fancy',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function breol_fancy_box_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );
}
