<?php

/**
 * @file
 * Module for making lists of content with fancy theming.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function breol_fancy_box_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_theme().
 */
function breol_fancy_box_theme($existing, $type, $theme, $path) {
  return array(
    'breol_fancy_box' => array(
      'variables' => array(
        'nodes' => array(),
      ),
      'path' => drupal_get_path('module', 'breol_fancy_box') . '/templates',
      'template' => 'fancy',
    ),
  );
}

/**
 * Implements hook_process_breol_fancy_box().
 */
function breol_fancy_box_process_breol_fancy_box(&$vars) {
  $nodes = array();
  foreach ($vars['nodes'] as $index => $node) {
    $view_mode = 'teaser_' . $vars['layout'][$index]['type'];
    $build = array(
      '#prefix' => '<div ' . drupal_attributes($vars['layout'][$index]['attributes']) . '>',
      '#suffix' => '</div>',
    );
    $build[] = node_view($node, $view_mode);
    $nodes[] = $build;
  }

  $vars['nodes'] = $nodes;
}

/**
 * Implements hook_preprocess_node().
 */
function breol_fancy_box_preprocess_node(&$variables, $hook) {
  if (!empty($variables['field_color'][0]['rgb'])) {
    $rgb = breol_fancy_box_hex2rgb($variables['field_color'][0]['rgb']);
    $variables['rgba_background'] = 'style="background:rgba(' . implode(",", $rgb) . ', 0.7);"';
  }

  $view_modes = array('teaser_small', 'teaser_medium');
  $node_types = array('link', 'breol_video', 'breol_news');

  if (in_array($variables['view_mode'], $view_modes) &&
    in_array($variables['type'], $node_types)) {

    $variables['teaser_title'] = $variables['title'];

    $link = $variables['node_url'];
    switch ($variables['type']) {
      case 'link':
        $summary = strip_tags(render($variables['content']['body']));
        $variables['teaser_type'] = t('link');
        $variables['teaser_caption'] = $summary;
        $link = $variables['field_breol_link'][0]['url'];
        break;

      case 'breol_video':
        $variables['teaser_type'] = t('video');
        $variables['teaser_caption'] = $variables['field_breol_video'][0]['filename'];
        break;

      case 'breol_news':
        $variables['teaser_type'] = t('news');
        $summary = strip_tags(render($variables['content']['body']));
        $variables['teaser_caption'] = $summary;
        break;
    }

    $variables['teaser_link'] = array(
      '#type' => 'link',
      '#title' => t('view more'),
      '#href' => $link,
    );
  }
}

/**
 * Get the layout structure of the fancy box.
 *
 * For now this is hardcoded, but in the feature this array might be editable
 * from the admin interface somehow.
 *
 * @return array
 *   The layouts with 'type' and 'attributes' keys.
 */
function breol_fancy_box_get_layout() {
  return array(
    array(
      'type' => 'medium',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
        ),
      ),
    ),
    array(
      'type' => 'small',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
        ),
      ),
    ),
    array(
      'type' => 'small',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
          'fancy-box__push-right',
        ),
      ),
    ),
    array(
      'type' => 'medium',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
        ),
      ),
    ),
    array(
      'type' => 'medium',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
          'fancy-box__push-left',
        ),
      ),
    ),
    array(
      'type' => 'small',
      'attributes' => array(
        'class' => array(
          'fancy-box-item',
        ),
      ),
    ),
  );
}

/**
 * Convert hex to rgb color value.
 */
function breol_fancy_box_hex2rgb($hex) {
  $hex = str_replace("#", "", $hex);

  if (strlen($hex) == 3) {
    $r = hexdec(substr($hex, 0, 1) . substr($hex, 0, 1));
    $g = hexdec(substr($hex, 1, 1) . substr($hex, 1, 1));
    $b = hexdec(substr($hex, 2, 1) . substr($hex, 2, 1));
  }
  else {
    $r = hexdec(substr($hex, 0, 2));
    $g = hexdec(substr($hex, 2, 2));
    $b = hexdec(substr($hex, 4, 2));
  }
  $rgb = array($r, $g, $b);

  return $rgb;
}
