<?php
/**
 * @file
 * Code for the eReolen loan module feature.
 */

include_once 'reol_loan.features.inc';
require_once 'includes/reol_loan.loan.inc';

/**
 * Implements hook_permission().
 */
function reol_loan_permission() {
  return array(
    'perform loan' => array(
      'title' => t('Perform loan'),
      'description' => t('Perform a loan of an audiobook or ebook'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function reol_loan_menu() {
  $items = array();

  $items['ting/object/%ting_object/loan'] = array(
    'page callback' => 'reol_loan_loan_ajax',
    'page arguments' => array(2),
    'delivery callback' => 'ajax_deliver',
    'access arguments' => array('perform loan'),
  );

  return $items;
}

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_loan_secure_permissions($role) {
  $permissions = array(
    'provider' => array(
      'perform loan',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function reol_loan_form_ding_loan_loans_form_alter(&$form, &$form_state) {
  // Move elements out of group. We do not wish to group items.
  foreach ($form['loans'] as $loan_group) {
    $children = element_children($loan_group);
    foreach ($children as $child) {
      if ($child == 'title') {
        continue;
      }
      $form['all_loans'][$child] = $loan_group[$child];

      // Add another information regarding when the loan expires.
      $loan = $form['all_loans'][$child]['#loan'];
      $time = strtotime(check_plain($loan->expiry));
      $time_diff = $time - time();

      // Add class according to how long time there is left.
      $class = " ";
      if ($time_diff < variable_get('reol_loan_low_time_max', 86400)) {
        $class .= 'low';
      }
      elseif ($time_diff < variable_get('reol_loan_medium_time_max', 604800)) {
        $class .= 'medium';
      }
      else {
        $class .= 'high';
      }

      $form['all_loans'][$child]['#information']['expire_in'] = array(
        'label' => t('Expires in'),
        'data' => format_interval($time - time(), 4),
        'class' => 'expires-in' . $class,
        '#weight' => 10,
      );

      // Change format of the two other dates.
      $form['all_loans'][$child]['#information']['loan_date']['data'] = format_date(strtotime(check_plain($loan->loan_date)), 'reol_base_material_lists_date');
      $form['all_loans'][$child]['#information']['expiry']['data'] = format_date(strtotime(check_plain($loan->expiry)), 'reol_base_material_lists_date');
    }
  }

  // Remove old groups.
  unset($form['loans']);
}

/**
 * Implements hook_ding_entity_buttons().
 *
 * Add loan button on entity view page for audiobook or ebook.
 */
function reol_loan_ding_entity_buttons($type, $entity) {
  if (reol_loan_is_right_type($entity) && reol_loan_is_available($entity)) {
    drupal_add_library('system', 'drupal.ajax');
    $buttons = array();

    $buttons[] = array(
      '#theme' => 'link',
      '#text' => t('Loan'),
      '#path' => 'ting/object/' . $entity->id . '/loan',
      '#options' => array(
        'attributes' => array(
          'class' => array(
            'action-button',
            'reserve-button',
            'use-ajax',
          ),
          'id' => 'loan-' . $entity->id,
        ),
        'html' => FALSE,
      ),
    );

    return $buttons;
  }
}

/**
 * Get the types we handle.
 *
 * @return array
 *   Array of types by their name in lower case.
 */
function _reol_loan_get_types() {
  return array(
    'lydbog (net)',
    'ebog',
  );
}

/**
 * Implements hook_ding_entity_is().
 */
function reol_loan_ding_entity_is($entity, $is) {
  // If title is available, set reservable to false to hide Ding reserve button.
  if ($is == 'reservable' && reol_loan_is_right_type($entity) && reol_loan_is_available($entity)) {
    return FALSE;
  }
}

/**
 * Implements hook_ding_entity_menu().
 *
 * Create menu callback for loaning an audiobook or ebook.
 */
function reol_loan_ding_entity_menu(&$items, $type, $path, $index) {
  if ($type == 'ding_entity') {
    $items[$path . '/loan'] = array(
      'title' => 'Loan',
      'page callback' => 'ding_provider_get_form',
      'page arguments' => array('reol_loan_loan_form', $index),
      'access callback' => TRUE,
    );
  }
}

/**
 * Check if an entity is available.
 *
 * @param TingEntity $entity
 *   The entity to check.
 *
 * @return bool
 *   Whether or not title is available.
 */
function reol_loan_is_available($entity) {
  if ($entity instanceof TingEntity) {
    // Only do anything if we if we are trying on a single entity,
    // not collection.
    $isbns = $entity->getIsbn();
    if (count($isbns) == 1) {
      $isbn = $isbns[0];

      // Check if title is available.
      list($availability) = array_values(ding_availability_items(array($isbn)));
      if ($availability['available']) {
        return TRUE;
      }
    }
  }

  // If we end up here, it is not available.
  return FALSE;
}

/**
 * Check if an entity is of one of the types we handle.
 *
 * @param TingEntity $entity
 *   The entity to check.
 *
 * @return bool
 *   Whether or not type is correct.
 */
function reol_loan_is_right_type($entity) {
  // Get types that we check for.
  $types = _reol_loan_get_types();

  // Actually check type, also check that we are trying on a single entity,
  // instead of a collection.
  if ($entity instanceof TingEntity && in_array(strtolower($entity->type), $types)) {
    $isbns = $entity->getIsbn();
    if (count($isbns) == 1) {
      return TRUE;
    }
  }

  // If we end up here, the type is not correct.
  return FALSE;

}
