<?php

/**
 * @file
 * Code for the ereol frontend feature.
 */

include_once 'ereol_frontend.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function ereol_frontend_entity_info_alter(&$entity_info) {
  $entity_info['ting_object']['view modes'] += array(
    'ereol_material_teaser' => array(
      'label' => t('eReol Material Teaser'),
      'custom settings' => TRUE,
    ),
  );
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function ereol_frontend_field_default_field_instances_alter(&$fields) {
  // Fields defined in ting_material_details.
  $detail_fields = array(
    'age',
    'audience',
    'classification',
    'contributor',
    'description',
    'extent',
    'format',
    'genre',
    'isbn',
    'ispartof',
    'language',
    'musician',
    'pegi',
    'publisher',
    'referenced',
    'replaced_by',
    'replaces',
    'rights',
    'source',
    'spatial',
    'spoken',
    'subjects',
    'subtitles',
    'tracks',
    'type',
    'uri',
    'version',
  );

  // Add our display mode to ting_material_details fields, to avoid it being
  // overridden.
  foreach ($detail_fields as $field) {
    if (isset($fields['ting_object-ting_object-ting_details_' . $field])) {
      $fields['ting_object-ting_object-ting_details_' . $field]['display'] += array(
        'ereol_material_teaser' => array(
          'label' => 'above',
          'type' => 'hidden',
        ),
        'latest' => array(
          'label' => 'above',
          'type' => 'hidden',
        ),
      );
    }
  }

  // Set image style on compact covers.
  if (isset($fields['ting_object-ting_object-ting_cover'])) {
    $fields['ting_object-ting_object-ting_cover']['display']['compact']['settings']['image_style'] = 'ereol_cover_base';
  }

  if (isset($fields['ting_object-ting_object-ting_series'])) {
    $fields['ting_object-ting_object-ting_series']['display']['teaser']['module'] = 'ting';
    $fields['ting_object-ting_object-ting_series']['display']['teaser']['type'] = 'ting_series_default';
  }
}

/**
 * Implements hook_field_group_info_alter().
 */
function ereol_frontend_field_group_info_alter(&$groups) {
  ksort($groups);
  if (isset($groups['group_inner|ting_object|ting_object|teaser'])) {
    $groups['group_inner|ting_object|ting_object|teaser']->data['children'][] = 'ting_series';
  }
}
