<?php

/**
 * @file
 * Provide a static tab which triggers a popup for sending a question to
 * Biblioteksvagten.dk.
 */

/**
 * Implements hook_menu().
 */
function ask_vopros_menu() {
  $items['admin/config/services/ask_vopros'] = array(
    'title' => 'Ask Vopros',
    'description' => 'Configure the tab for sending user questions to a Vopros site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ask_vopros_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ask_vopros.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ask_vopros_theme() {
  return array(
    'ask_vopros_opening_hours' => array(
      'render element' => 'elements',
      'file' => 'ask_vopros.admin.inc',
    ),
  );
}

/**
 * Preprocess variables for html.tpl.php
 *
 * This adds in our bottom tab. Using hook_page_build() is no good, as
 * panels_everywhere thoroughly disables it, so we use this instead.
 */
function ask_vopros_preprocess_html(&$vars) {
  global $user;
  $agency_id = variable_get('ask_vopros_agency_id', _ask_vopros_ting_agency_id());

  if (!$agency_id) {
    return;
  }

  // JavaScript settings var. Basic settings, id and mail.
  $widget_settings = array(
    'agency_id' => $agency_id,
    'agency_mail' => variable_get('ask_vopros_agency_mail', variable_get('site_mail', '')),
  );

  $answer_preference = variable_get('ask_vopros_answer_preference', 'mail');
  if ($answer_preference !== 'mail') {
    $widget_settings['answer_preference'] = $answer_preference;
  }

  // Check if a ding user is logged in and add in their name/zip/mail/phone if
  // they are.
  if (function_exists('ding_user_provider_profile') && $profile = ding_user_provider_profile($user)) {
    $module = ding_provider_get_provider_module_name('user');
    $mapping = array(
      'name' => 'full_name',
      'zip' => 'postal_code',
      'phone' => 'mobile_phone',
    );

    foreach ($mapping as $name => $field_suffix) {
      $field_name = 'field_' . $module . '_' . $field_suffix;

      $field_value = field_get_items('profile2', $profile, $field_name);
      if (!empty($field_value[0]['value'])) {
        $widget_settings[$name] = $field_value[0]['value'];
      }
    }

    // Seems that there's some trouble getting the mail address from the
    // profile. It should've been copied to the mail of the Drupal user, so use
    // that.
    if (!empty($user->mail)) {
      $widget_settings['mail'] = $user->mail;
    }
  }

  // Check visibility settings. We add the query argument to get
  // question_modal.js to add the tab for us.
  $visibility_type = variable_get('ask_vopros_visibility_type', 'not on');
  $visibility_pages = variable_get('ask_vopros_visibility_pages', '');
  // The default visibility in case $visibility_pages is empty.
  $visible = $visibility_type == 'not on';

  // If no pages are specified, show regardless of the type. This logic was
  // lifted from block_block_list_alter(). Look there for comments.
  if ($visibility_pages) {
    $visibility_pages = drupal_strtolower($visibility_pages);
    $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
    $page_match = drupal_match_path($path, $visibility_pages);
    if ($path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $visibility_pages);
    }

    $visible = ($visible xor $page_match);
  }

  $settings = array();
  $settings['ask_vopros_opening_hours'] = _ask_vopros_opening_hours_today(variable_get('ask_vopros_opening_hours', array()));

  $widget_settings_js = 'var ask_vopros = ' . json_encode($widget_settings) . ';';
  $widget_settings_js .= 'var ask_vopros_offset = ' . (time() * 1000) . ' - Date.now();';

  // Add the settings.
  $attachments = array(
    'js' => array(
      array('data' => $settings, 'type' => 'setting'),
      array('data' => $widget_settings_js, 'type' => 'inline'),
      drupal_get_path('module', 'ask_vopros') . '/js/ask_vopros.js',
    ),
    'css' => array(),
  );

  $right = variable_get('ask_vopros_right', '');

  $color = variable_get('ask_vopros_color', '');
  if (!empty($color)) {
    $css = <<<EOF
body.html .ask-vopros-tab,
body.html .ask-vopros-tab .ask-vopros-icon,
body.html .ask-vopros-tab .ask-vopros-text,
body.html .ask-vopros-tab .ask-vopros-minimize {
  background-color: $color;
}
EOF;
    $attachments['css'][] = array(
      'data' => $css,
      'type' => 'inline',
    );
  }

  $tabs = array(
    'external' => variable_get('ask_vopros_uri', 'http://adm.biblioteksvagten.dk'),
    'local' => variable_get('ask_vopros_secondary_uri', ''),
  );

  foreach ($tabs as $class => $base) {
    if (empty($base)) {
      continue;
    }
    $base = rtrim($base, '/') . '/embed/';

    // We can't set the async attribute for an attached JS, so we build the
    // script element by hand, in the same way drupal_get_js() does. Using
    // async and defer is the currently recommend practice to avoid having the
    // page hang on the script. @see
    // https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/
    $element = array(
      '#tag' => 'script',
      '#value' => '',
      '#attributes' => array(
        'type' => 'text/javascript',
        'src' => $base . 'question_modal.js?class=' . $class . ($visible ? '&tab=true' : ''),
        'defer' => 'defer',
        'async' => 'async',
      ),
    );

    $element = array(
      '#markup' => theme('html_tag', array('element' => $element)),
    );

    // Need to add the margin for each class, as we can't fix it with
    // specificity.
    if (!empty($right) || $right === '0') {
      $attachments['css'][] = array(
        'data' => 'body .ask-vopros-tab.' . $class . ' {right: ' . $right . '}',
        'type' => 'inline',
      );
    }

    // Only attach once.
    if ($attachments) {
      $element['#attached'] = $attachments;
      $attachments = NULL;
    }
    // Hide tabs per default.
    $element['#attached']['css'][] = array(
      'data' => 'body .ask-vopros-tab.' . $class . ' {display: none}',
      'type' => 'inline',
    );

    $vars['page']['page_bottom'][] = $element;
  }
}

/**
 * Glean agency_id from ting.module.
 *
 * Checks if ting.module has been configured with an agency, and use that to
 * create ours.
 *
 * @return string|null
 *   Agency id or null if not found.
 */
function _ask_vopros_ting_agency_id() {
  if ($agency_id = variable_get('ting_agency', '')) {
    return 'DK-' . $agency_id;
  }

  return NULL;
}

/**
 * Get opening hours for today for JavaScript.
 */
function _ask_vopros_opening_hours_today($opening_hours) {
  $day = date('N') - 1;
  $time = new DateTime();
  $time->setTime(0, 0, 0);
  $times = array(
    'open' => NULL,
    'close' => NULL,
  );
  foreach (array('open', 'close') as $state) {
    if ($opening_hours[$state][$day]) {
      list($hours, $minutes) = explode(':', $opening_hours[$state][$day]);
      $time->setTime($hours, $minutes, 0);
      // JS timestamps is in milliseconds.
      $times[$state] = $time->format('U') * 1000;
    }
  }
  return $times;
}
