<?php
/**
 * @file
 * Main module that attach lazy loading to images.
 */

/**
 * Implements hook_init().
 */
function reol_lazy_load_images_init() {
  drupal_add_js(drupal_get_path('module', 'reol_lazy_load_images') . '/js/reol_lazy_load_images.js');
}

/**
 * Implements hook_image_effect_info().
 */
function reol_lazy_load_images_image_effect_info() {
  $effects = [];

  $effects['reol_lazy_load_images_placeholder'] = [
    'label' => t('Create placeholder image'),
    'help' => t('Create blurred minimal placeholder image'),
    'effect callback' => 'reol_lazy_load_images_placeholder_effect',
    'dimensions passthrough' => TRUE,
  ];

  return $effects;
}

/**
 * Image effect callback function.
 *
 * Resizes the image to 5px with the same aspect rations.
 *
 * @param stdClass $image
 *   The image style use the effect on.
 *
 * @return bool
 *   TRUE if style can be applied else FALSE.
 */
function reol_lazy_load_images_placeholder_effect(stdClass $image) {
  $image->ops[] = '-resize 5x';
  $image->ops[] = '-strip';

  return TRUE;
}

/**
 * Implements hook_image_default_styles().
 */
function reol_lazy_load_images_image_default_styles() {
  $styles = [];

  // New style that can be used to generate the placeholders for cover images.
  // It's base on the eReol_base_cover style.
  $styles['reol_lazy_load_images_cover_placeholder'] = [
    'label' => 'reol_lazy_cover_placeholder',
    'effects' => [
      1 => [
        'name' => 'image_scale_and_crop',
        'data' => [
          'width' => 260,
          'height' => 375,
        ],
        'weight' => 1,
      ],
      2 => [
        'name' => 'reol_lazy_load_images_placeholder',
        'weight' => 2,
      ]
    ],
  ];

  return $styles;
}

/**
 * Implements hook_theme_registry_alter().
 */
function reol_lazy_load_images_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['image'])) {
    $theme_registry['image']['function'] = 'theme_reol_base_image';
  }
}

/**
 * Image theme function.
 *
 * Insert the "mini" image as source for images with style "ereol_cover_base"
 * and the real image as data-src for lazy loading.
 */
function theme_reol_base_image($variables) {
  $attributes = $variables['attributes'];

  if (array_key_exists('style_name', $variables) && $variables['style_name'] == 'ereol_cover_base') {
    $attributes['data-src'] = file_create_url($variables['path']);
    $attributes['src'] = image_style_url('reol_lazy_load_images_cover_placeholder', $variables['original_path']);;
    $attributes['class'] = 'js-lazy';
  }
  else {
    $attributes['src'] = file_create_url($variables['path']);
  }

  foreach (array('width', 'height', 'alt', 'title') as $key) {
    if (isset($variables[$key])) {
      $attributes[$key] = $variables[$key];
    }
  }

  return '<img' . drupal_attributes($attributes) . ' />';
}
