<?php
/**
 * @file
 * Code for the BReol frontend feature.
 */

include_once 'breol_frontend.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function breol_frontend_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_theme().
 */
function breol_frontend_theme($existing, $type, $theme, $path) {
  return array(
    'cover_image' => array(
      'variables' => array(
        'image_uri' => NULL,
        'cover_background_color' => 'transparant',
        'title' => '',
        'subtitle' => '',
        'node'  => NULL,
      ),
      'path' => drupal_get_path('module', 'breol_frontend') . '/templates',
      'template' => 'cover-image',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function breol_frontend_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Copied from
 * reol_frontend_form_profile2_edit_provider_publizon_form_alter().
 */
function breol_frontend_form_profile2_edit_provider_publizon_form_alter(&$form, &$form_state) {
  // Hide retailer id.
  $form['profile_provider_publizon']['field_publizon_retailer_id']['#access'] = FALSE;

  // Hide pass change fieldset.
  $form['pass']['#access'] = FALSE;

  // Hide sms fee.
  $form['ding_user_fee_sms']['#access'] = FALSE;
}
