<?php
/**
 * @file
 * Code for the BReol frontend feature.
 */

include_once 'breol_frontend.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function breol_frontend_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Copied from
 * reol_frontend_form_profile2_edit_provider_publizon_form_alter().
 */
function breol_frontend_form_profile2_edit_provider_publizon_form_alter(&$form, &$form_state) {
  // Hide retailer id.
  $form['profile_provider_publizon']['field_publizon_retailer_id']['#access'] = FALSE;

  // Hide pass change fieldset.
  $form['pass']['#access'] = FALSE;

  // Hide sms fee.
  $form['ding_user_fee_sms']['#access'] = FALSE;
}
