<?php
/**
 * @file
 * Code for the BReol frontend feature.
 */

include_once 'breol_frontend.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function breol_frontend_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_theme().
 */
function breol_frontend_theme($existing, $type, $theme, $path) {
  return array(
    'cover_image' => array(
      'variables' => array(
        'image_uri' => NULL,
        'cover_background_color' => 'transparant',
        'title' => '',
        'subtitle' => '',
        'node'  => NULL,
      ),
      'path' => drupal_get_path('module', 'breol_frontend') . '/templates',
      'template' => 'cover-image',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function breol_frontend_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['node']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_small'] = array(
    'label' => t('Teaser Small'),
    'custom settings' => TRUE,
  );

  $entity_info['file']['view modes']['teaser_medium'] = array(
    'label' => t('Teaser Medium'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Copied from
 * reol_frontend_form_profile2_edit_provider_publizon_form_alter().
 */
function breol_frontend_form_profile2_edit_provider_publizon_form_alter(&$form, &$form_state) {
  // Hide retailer id.
  $form['profile_provider_publizon']['field_publizon_retailer_id']['#access'] = FALSE;

  // Hide pass change fieldset.
  $form['pass']['#access'] = FALSE;

  // Hide sms fee.
  $form['ding_user_fee_sms']['#access'] = FALSE;
}

/**
 * Implements hook_default_page_manager_pages_alter().
 *
 * Override the bookmark page.
 */
function breol_frontend_default_page_manager_pages_alter(&$pages) {
  $page = new stdClass();
  $page->disabled = FALSE; /* Edit this to true to make a default page disabled initially */
  $page->api_version = 1;
  $page->name = 'user_bookmarks';
  $page->task = 'page';
  $page->admin_title = 'User bookmarks';
  $page->admin_description = '';
  $page->path = 'user/%user/bookmarks';
  $page->access = array(
    'logic' => 'and',
    'plugins' => array(
      0 => array(
        'name' => 'compare_users',
        'settings' => array(
          'equality' => '1',
        ),
        'context' => array(
          0 => 'logged-in-user',
          1 => 'argument_entity_id:user_1',
        ),
        'not' => FALSE,
      ),
    ),
    'type' => 'none',
    'settings' => NULL,
  );
  $page->menu = array(
    'type' => 'tab',
    'title' => 'Bookmarks',
    'name' => 'navigation',
    'weight' => '3',
    'parent' => array(
      'type' => 'none',
      'title' => '',
      'name' => 'navigation',
      'weight' => '0',
    ),
  );
  $page->arguments = array(
    'user' => array(
      'id' => 1,
      'identifier' => 'User',
      'name' => 'entity_id:user',
      'settings' => array(),
    ),
  );
  $page->conf = array(
    'admin_paths' => FALSE,
  );
  $page->default_handlers = array();
  $handler = new stdClass();
  $handler->disabled = FALSE; /* Edit this to true to make a default handler disabled initially */
  $handler->api_version = 1;
  $handler->name = 'page_user_bookmark_panel_context';
  $handler->task = 'page';
  $handler->subtask = 'user_bookmarks';
  $handler->handler = 'panel_context';
  $handler->weight = 0;
  $handler->conf = array(
    'title' => 'Panel',
    'no_blocks' => 0,
    'pipeline' => 'standard',
    'css_id' => 'user-bookmarks',
    'css' => '',
    'contexts' => array(),
    'relationships' => array(),
  );
  $display = new panels_display();
  $display->layout = 'stacked_columns';
  $display->layout_settings = array();
  $display->panel_settings = array(
    'style_settings' => array(
      'default' => NULL,
      'middle' => NULL,
      'left' => NULL,
      'right' => NULL,
      'left_sidebar' => NULL,
      'main_content' => NULL,
      'right_sidebar' => NULL,
      'attachment_4_1' => NULL,
      'attachment_4_2' => NULL,
      'attachment_4_3' => NULL,
      'attachment_4_4' => NULL,
      'attachment_3_1' => NULL,
      'attachment_3_2' => NULL,
      'attachment_3_3' => NULL,
      'attachment_2_1' => NULL,
      'attachment_2_2' => NULL,
      'attachment_1_1' => NULL,
      'header' => NULL,
      'before_content' => NULL,
      'after_content' => NULL,
      'bottom' => NULL,
    ),
  );
  $display->cache = array();
  $display->title = 'My bookmarks';
  $display->uuid = '5c12fb2f-0dd6-4879-8a57-035574cc03fc';
  $display->content = array();
  $display->panels = array();
  $pane = new stdClass();
  $pane->pid = 'new-3d86446d-d17a-4d20-80c2-72809fca9aa4';
  $pane->panel = 'main_content';
  $pane->type = 'bookmarks';
  $pane->subtype = 'bookmarks';
  $pane->shown = TRUE;
  $pane->access = array();
  $pane->configuration = array(
    'context' => 'argument_entity_id:user_1',
    'override_title' => 0,
    'override_title_text' => '',
  );
  $pane->cache = array();
  $pane->style = array(
    'settings' => NULL,
  );
  $pane->css = array();
  $pane->extras = array();
  $pane->position = 0;
  $pane->locks = '';
  $pane->uuid = '3d86446d-d17a-4d20-80c2-72809fca9aa4';
  $display->content['new-3d86446d-d17a-4d20-80c2-72809fca9aa4'] = $pane;
  $display->panels['main_content'][0] = 'new-3d86446d-d17a-4d20-80c2-72809fca9aa4';
  $display->hide_title = PANELS_TITLE_FIXED;
  $display->title_pane = '0';
  $handler->conf['display'] = $display;
  $page->default_handlers[$handler->name] = $handler;

  $pages['user_bookmarks'] = $page;
}
