<?php
$plugin = array(
  'title'     => t('Wille Site template'),
  'theme'     => 'wille_site_template',
  'icon'      => 'wille_site_template.png',
  'category'  => 'Wille, theme',
  'regions' => array(
    'branding'        => t('Branding'),
    'header'          => t('Header'),
    'navigation'      => t('Navigation'),
    'content_header'  => t('Main content header'),
    'content'         => t('Main content'),
    'footer'          => t('Footer'),
    'bottom'          => t('Bottom'),
  ),
);
