<?php
/**
 * @file
 * Code for the eReolen base module feature.
 */

define('REOL_BASE_LOCAL_ID_PREFIX', 'isbn_');

/**
 * Get the field form for a field.
 *
 * @param string $type
 *   The entity type to get field for.
 * @param string $bundle
 *   The entity bundle for the entity.
 * @param string $field_name
 *   The name of the field.
 * @param StdClass $entity
 *   The entity to get field for.
 * @param array $form
 *   The form to attach field to.
 * @param array $form_state
 *   The state of the form.
 *
 * @return array
 *   The field form.
 */
function reol_base_get_field_form($type, $bundle, $field_name, $entity, &$form, &$form_state) {
  $field = field_info_field($field_name);
  $instance = field_info_instance($type, $field_name, $bundle);
  $lang_code = field_language($type, $entity, $field_name);
  $items = field_get_items($type, $entity, $field_name);
  return field_default_form($type, $entity, $field, $instance, $lang_code, $items, $form, $form_state);
}

/**
 * Implements hook_entity_load().
 *
 * As our provider uses ISBN-numbers, we wish to have localId be the
 * ISBN-number of the object.
 */
function reol_base_entity_load($entities, $type) {
  // Only act on our own type.
  if ($type != 'ting_object') {
    return;
  }

  foreach ($entities as $entity) {
    if (!($entity instanceof TingEntity)) {
      continue;
    }
    // When have to check all the way down, as chain might be broken
    // somwhere. Only touch localId if we have the right value for it.
    if (isset($entity->reply) &&
      isset($entity->reply->record) &&
      isset($entity->reply->record['dc:identifier'])) {
      $local_id = FALSE;

      // Try to find the id we need in oss:PROVIDER-ID.
      if (isset($entity->reply->record['dc:identifier']['oss:PROVIDER-ID']) &&
        count($entity->reply->record['dc:identifier']['oss:PROVIDER-ID'] == 1)) {
        $local_id = reol_base_get_local_id($entity->reply->record['dc:identifier']['oss:PROVIDER-ID']);
      }
      // If not found there, look in dkdcplus:ISBN.
      elseif (isset($entity->reply->record['dc:identifier']['dkdcplus:ISBN']) &&
        count($entity->reply->record['dc:identifier']['dkdcplus:ISBN'])) {
        $local_id = reol_base_get_local_id($entity->reply->record['dc:identifier']['dkdcplus:ISBN']);
      }

      if ($local_id) {
        $entity->localId = $local_id;
      }
    }
  }
}

/**
 * Convert an array of ISBN-numbers to a local id.
 *
 * @param mixed $isbns
 *   The ISBN number array to convert.
 *
 * @return string
 *   The localId string.
 */
function reol_base_get_local_id($isbns) {
  // Make sure it is array,
  if (!is_array($isbns)) {
    $isbns = array($isbns);
  }

  $num = FALSE;
  foreach ($isbns as $isbn) {
    $isbn = str_replace('-', '', $isbn);
    // ISBN is the first 13-length number found.
    if (strlen($isbn) == 13) {
      $num = $isbn;
      break;
    }
  }

  // We have no ISBN-number to use.
  if (!$num) {
    return FALSE;
  }

  // Add our prefix and remove dashes that might appear.
  // We add the prefix to avoid strange conflicts with entities
  // that have their local id defined as the ISBN-number.
  return REOL_BASE_LOCAL_ID_PREFIX . $num;
}

/**
 * Convert the local id to an ISBN number.
 *
 * @param string $local_id
 *   The local id.
 *
 * @return string
 *   The ISBN number.
 */
function reol_base_get_isbn($local_id) {
  // Remove prefix in front, if found.
  // If not, it is not an ISBN-number.
  if (strpos($local_id, REOL_BASE_LOCAL_ID_PREFIX) === 0) {
    return substr($local_id, strlen(REOL_BASE_LOCAL_ID_PREFIX));
  }
  return FALSE;
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Change material_item to use our template instead.
 */
function reol_base_theme_registry_alter(&$theme_registry) {
  $theme_registry['material_item']['template'] = drupal_get_path('module', 'reol_base') . '/templates/material_item';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function reol_base_preprocess_material_item(&$variables) {
  $element = $variables['element'];
  $ting_entity = ding_entity_load($element['#id']);

  $variables['type'] = reol_base_get_type_name($ting_entity->type);

  // Put buttons from entity view on list.
  $buttons = field_view_field('ting_object', $ting_entity, 'ding_entity_buttons', 'default');
  $variables['buttons'] = drupal_render($buttons);
}

/**
 * Get the name of a type from the type returned from Ting.
 *
 * If type is not input, it returns an array of names of
 * types we support.
 *
 * @param string $type
 *   The string type from Ting.
 *
 * @return string
 *   Our own name for the type, or array of type names if no type is input,
 *   keyed by our name type.
 *   If type is not found, FALSE is returned.
 */
function reol_base_get_type_name($type = FALSE) {
  $types = array(
    'lydbog (net)' => 'audiobook',
    'ebog' => 'ebook',
  );

  return !$type ? array_flip($types) : (isset($types[strtolower($type)]) ? $types[strtolower($type)] : FALSE);
}

/**
 * Implements hook_date_format_Types().
 */
function reol_base_date_format_types() {
  return array(
    'reol_base_material_lists_date' => t('Reol material lists date'),
  );
}
/**
 * Implements hook_date_formats().
 */
function reol_base_date_formats() {
  return array(
    array(
      'type' => 'reol_base_material_lists_date',
      'format' => 'j. F Y H:i:s',
      'locales' => array(),
    ),
  );
}

/**
 * Convert a string to an ISBN-13 number.
 *
 * @param string $isbn
 *   The isbn-number to convert.
 *
 * @return string|bool
 *   The ISBN-numer if input is an ISBN-13 number. False otherwise.
 */
function reol_base_convert_to_isbn($isbn) {
  $isbn = str_replace(array(' ', '-'), '', $isbn);
  return preg_match('/^[0-9]{13}$/', $isbn) ? $isbn : FALSE;
}
