<?php

/**
 * @file
 * Shared frontend code.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function reol_shared_frontend_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_drupal_goto_alter().
 *
 * Remove the fragment from the redirect to <front> by ding_user. We don't have
 * the #login form and JS of DDBasic, so it's a no-op and looks weird.
 */
function reol_shared_frontend_drupal_goto_alter(&$path, &$options) {
  if ($path == '' &&
    isset($options['fragment']) &&
    $options['fragment'] == 'login') {
    unset($options['fragment']);
  }
}
