<?php

/**
 * @file
 * Shared frontend code.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function reol_shared_frontend_ctools_plugin_directory($owner, $plugin_type) {
  return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_drupal_goto_alter().
 *
 * Remove the fragment from the redirect to <front> by ding_user. We don't have
 * the #login form and JS of DDBasic, so it's a no-op and looks weird.
 */
function reol_shared_frontend_drupal_goto_alter(&$path, &$options) {
  if ($path == '' &&
    isset($options['fragment']) &&
    $options['fragment'] == 'login') {
    unset($options['fragment']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for search_block_form().
 *
 * Disable ting_search_autocompletes autocomplete, we don't use it. Ideally we'd
 * just disable the module, but ding_ting_frontend depends on it.
 *
 * @see reol_shared_frontend_module_implements_alter()
 * @deprecated Moved to reol_frontend.
 */
function reol_shared_frontend_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    if (isset($form['search_block_form']['#autocomplete_path'])) {
      unset($form['search_block_form']['#autocomplete_path']);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Adjusts hooks so we get in after
 * ting_search_autocomplete_form_search_block_form_alter().
 *
 * @deprecated Moved to reol_frontend.
 */
function reol_shared_frontend_module_implements_alter(&$implementations, $hook) {
  // You'd think we should look for form_search_block_form_alter, but, no.
  if ($hook == 'form_alter' &&
    isset($implementations['reol_shared_frontend'])) {
    $group = $implementations['reol_shared_frontend'];
    unset($implementations['reol_shared_frontend']);
    $implementations['reol_shared_frontend'] = $group;
  }
}
