<?php
/**
 * @file
 * Code for the BReol frontpage feature.
 */

include_once 'breol_frontpage.features.inc';

/**
 * Implements hook_ting_post_execute().
 *
 * Adds the quota status to the ting object response.
 */
function breol_frontend_ting_post_execute($request, $response, $raw_response) {
  switch (get_class($response)) {
    case 'TingClientObject':
      $response->on_quota = TRUE;
      if (isset($raw_response->searchResponse->result->searchResult[0]->collection->object[0]->collection->record)) {
        $response->on_quota = _reol_frontend_is_quotaed($raw_response->searchResponse->result->searchResult[0]->collection->object[0]->collection->record);
      }

      break;

    case 'TingClientObjectCollection':
      foreach ($response->objects as $key => $object) {
        $object->on_quota = TRUE;
        if (isset($raw_response->searchResponse->result->searchResult[0]->collection->object[$key]->collection->record)) {
          $object->on_quota = _reol_frontend_is_quotaed($raw_response->searchResponse->result->searchResult[0]->collection->object[$key]->collection->record);
        }
      }
      break;

    case 'TingClientSearchResult':
      foreach ($response->collections as $col_key => $object_collection) {
        foreach ($object_collection->objects as $key => $object) {
          $object->on_quota = TRUE;
          if (isset($raw_response->searchResponse->result->searchResult[$col_key]->collection->object[$key]->collection->record)) {
            $object->on_quota = _reol_frontend_is_quotaed($raw_response->searchResponse->result->searchResult[$col_key]->collection->object[$key]->collection->record);
          }
        }
      }
      break;
  }
}
