# A sample Guardfile
# More info at https://github.com/guard/guard#readme

ignore %r{_flymake\.}
ignore %r{flycheck_}
ignore %r{\.#}
guard 'livereload' do
  watch(%r{\.(css|js|html)})
end

# Guard::Compass
#
# You don't need to configure watchers for guard 'compass' declaration as they generated
# from your Compass configuration file. You might need to define the Compass working directory
# and point to the configuration file depending of your project structure.
#
# Available options:
#
# * working_directory: Define the Compass working directory, relative to the Guardfile directory
# * configuration_file: Path to the Compass configuration file, relative to :project_path
#
# Like usual, the Compass configuration path are relative to the :project_path

guard 'compass', project_path: '.', configuration_file: 'config.rb'

