<?php
$plugin['stacked_columns'] = array(
  'title' => t('Wille Stacked Columns'),
  'icon' => '25_50_25.png',
  'theme' => 'stacked_columns',
  'category'  => 'Wille, theme',
  'regions' => array(
    'header' => t('Header Content'),
    'before_content' => t('Before content'),
    'main_content' => t('Main Contnent'),
    'after_content' => t('After Content'),
    'bottom' => t('Bottom'),
  ),
);
