<?php

/**
 * @file
 * Module file for reol_widget.
 */

use Drupal\reol_widget\Controller\SearchController;

/**
 * Implements hook_menu().
 */
function reol_widget_menu() {
  $items['widget/search'] = [
    'page callback' => 'reol_widget_search',
    'access arguments' => ['access content'],
    'delivery callback' => 'reol_widget_deliver_json',
  ];

  return $items;
}

/**
 * Deliver JSON result.
 */
function reol_widget_deliver_json($result) {
  drupal_json_output($result);
  exit;
}

/**
 * Search.
 */
function reol_widget_search() {
  $controller = new SearchController();
  return $controller->search();
}
