<?php

/**
 * @file
 * Code for the Newsletter paragraph feature.
 */

include_once 'reol_newsletter_paragraph.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function reol_newsletter_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'newsletter_signup') {
      $signup = mailchimp_signup_load('newsletter_signup');
      $form = drupal_get_form('mailchimp_signup_subscribe_block_' . $signup->name . '_form', $signup, 'mailchimp_signup_block');
      $variables['content'] = array(
        'signup' => $form,
      );
    }
  }
}
