<?php

/**
 * @file
 * Statistics of loans.
 */

define('REOL_STATISTICS_DEFAULT_TITLE', 'Statistics for loans by UNI•Login users');
define('REOL_STATISTICS_DEFAULT_HEADER', "Dato: @date\nKommunenavn: @municipality\nTilmeldte elever i kommunen: @subscribed_users");

/**
 * Implements hook_publizon_loan().
 */
function reol_statistics_publizon_loan($account, $name, $isbn, $retailer_id) {
  // We generate an unique hash from our private key and user uid. Hopefully
  // this is enough disassociation between user and loans.
  $user_hash = hash('sha512', drupal_get_private_key() . $account->uid);
  $data = array(
    'timestamp' => REQUEST_TIME,
    'retailer_id' => $retailer_id,
    'user_hash' => $user_hash,
    'isbn' => $isbn,
  );
  $unilogin_data = array();

  // Catch all exceptions and ignore them.
  try {
    // Add Unilogin data, if possible.
    if (function_exists('ding_unilogin_authenticated') &&
      ding_unilogin_authenticated($account)) {
      $service = ding_unilogin_wservice('info');
      $person = $service->getPerson($name);
      if (!$person) {
        watchdog(
          'reol_statistics',
          'Cannot get person for %user.',
          array('%user' => $name),
          WATCHDOG_ERROR
        );
      }

      $inst = $service->getInstitution($person->Instnr);
      if (!$inst) {
        watchdog(
          'reol_statistics',
          'Cannot get institution id %institution_id for %user.',
          array('%user' => $name, '%institution_id' => $person->Instnr),
          WATCHDOG_ERROR
        );
      }
      else {
        $unilogin_data['school_id'] = $inst->Instnr;
        $unilogin_data['school'] = $inst->Navn;
        $unilogin_data['municipality_id'] = $inst->Kommunenr;
        $unilogin_data['municipality'] = $inst->Kommune;
      }

      $student = $service->getStudent($person->Instnr, $person->Brugerid);
      if (!$student) {
        watchdog(
          'reol_statistics',
          'Cannot  get student record for user id %user_id at institution id %institution_id.',
          array(
            '%user' => $name,
            '%user_id' => $person->Brugerid,
            '%institution_id' => $person->Instnr,
          ),
          WATCHDOG_ERROR
        );
      }
      else {
        $unilogin_data['class'] = $student->Klasse;
      }
    }
  }
  catch (Exception $e) {
    // Quietly ignore.
  }

  $sid = db_insert('reol_statistics_loans')
    ->fields($data)
    ->execute();

  if ($sid && $unilogin_data) {
    $unilogin_data['sid'] = $sid;
    db_insert('reol_statistics_unilogin')
      ->fields($unilogin_data)
      ->execute();
  }
}

/**
 * Implements hook_menu().
 */
function reol_statistics_menu() {
  $items = array();

  $items['statistics'] = array(
    'title' => 'Select municipality',
    'page callback' => 'reol_statistics_select_municipality_page',
    // Let anyone see statistics (let's see if anyone complains).
    'access callback' => TRUE,
    'file' => 'reol_statistics.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['statistics/%reol_statistics_municipality/%reol_statistics_month/%reol_statistics_month'] = array(
    'title' => 'Statistics',
    'title callback' => 'variable_get',
    'title arguments' => array('reol_statistics_title', REOL_STATISTICS_DEFAULT_TITLE),
    'page callback' => 'reol_statistics_municipality_page',
    'page arguments' => array(1, 2, 3),
    // Let anyone see statistics (let's see if anyone complains).
    'access callback' => TRUE,
    'file' => 'reol_statistics.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/ereolen/statistics'] = array(
    'title' => 'Statistics',
    'description' => 'Configure statistics.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('reol_statistics_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'reol_statistics.admin.inc',
  );

  return $items;
}

/**
 * Menu loader.
 */
function reol_statistics_month_load($string) {
  if (preg_match('/^\d{6}$/', $string)) {
    return ReolStatisticsMonth::fromInt($string);
  }

  return FALSE;
}

/**
 * Menu loader.
 */
function reol_statistics_municipality_load($string) {
  if (preg_match('/^\d+$/', $string)) {
    $library = publizon_get_library($string);
    if (!empty($library)) {
      return $library;
    }
  }

  return FALSE;
}

/**
 * Implements hook_cron().
 */
function reol_statistics_cron() {
  $statistics = reol_statistics_get();

  foreach ($statistics as $statistic) {
    $varname = 'reol_statistics_last_queued_' . get_class($statistic);
    $month = ReolStatisticsMonth::fromInt(variable_get($varname, 201609));
    reol_statistics_ensure_schema($statistic);

    while (!$month->isCurrent()) {
      $month = $month->next();
      $queue = DrupalQueue::get('statistics_backlog_processing');
      $payload = array(
        'class' => get_class($statistic),
        'month' => $month->toInt(),
      );
      $queue->createItem($payload);
      variable_set($varname, $month->toInt());
    }

    // Always queue a run of the current month.
    $queue = DrupalQueue::get('statistics_processing');
    $payload = array(
      'class' => get_class($statistic),
      'month' => $month->toInt(),
    );
    $queue->createItem($payload);
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function reol_statistics_cron_queue_info() {
  // Processing of current month.
  $queues['statistics_processing'] = array(
    'worker callback' => 'reol_statistics_worker',
    'time' => 120,
  );

  // Backlog processing.
  $queues['statistics_backlog_processing'] = array(
    'worker callback' => 'reol_statistics_worker',
    'time' => 120,
  );

  return $queues;
}

/**
 * Cron worker callback.
 *
 * Collects statistics for one month for one statistic.
 */
function reol_statistics_worker($data) {
  $class = $data['class'];
  $statistic = new $class();
  $statistic->collect(ReolStatisticsMonth::fromInt($data['month']));
}

/**
 * Returns statistics classes.
 */
function reol_statistics_get() {
  $classes = &drupal_static(__FUNCTION__, NULL);

  if (!$classes) {
    $classes = array(
      new ReolStatisticsMunicipality(),
      new ReolStatisticsSchool(),
      new ReolStatisticsISBN(),
    );
  }

  return $classes;
}

/**
 * Ensure that statistics schema is up to date.
 */
function reol_statistics_ensure_schema(ReolStatisticsInterface $statistic) {
  $reset = FALSE;
  $schema = $statistic->schema();
  foreach ($schema as $table => $def) {
    $hash = md5(serialize($def));
    if ($hash != variable_get($table . '_md5', NULL)) {
      // Schema changed, rebuild.
      db_drop_table($table);
      db_create_table($table, $def);
      variable_set($table . '_md5', $hash);
      $reset = TRUE;
    }
  }

  if ($reset && method_exists($statistic, 'reset')) {
    $statistic->reset();
  }
}

/**
 * Reset statistics, causing a rerun.
 */
function reol_statistics_reset_all() {
  $statistics = reol_statistics_get();

  foreach ($statistics as $statistic) {
    reol_statistics_reset($statistic);
  }
}

/**
 * Reset a statistic.
 */
function reol_statistics_reset(ReolStatisticsInterface $statistic) {
  $varname = 'reol_statistics_last_queued_' . get_class($statistic);
  $schema = $statistic->schema();
  foreach (array_keys($schema) as $table) {
    // Delete table. It will be recreated.
    db_drop_table($table);
    variable_del($table . '_md5');
  }
  variable_del($varname);
}

/**
 * Interface for the statistics classes.
 */
interface ReolStatisticsInterface {

  /**
   * Returns schema for this statistic.
   */
  public function schema();

  /**
   * Collect this statistic.
   *
   * Run in cron.
   *
   * @param ReolStatisticsMonth $month
   *   Month to collect statistics for.
   */
  public function collect(ReolStatisticsMonth $month);

  /**
   * Build statistic display.
   *
   * @param array library
   *   The library as returned from publizon_get_library().
   * @param ReolStatisticsMonth $from
   *   From date, integer in yyyymm format.
   * @param ReolStatisticsMonth $to
   *   To date, integer in yyyymm format, inclusive.
   */
  public function build(array $library, ReolStatisticsMonth $from, ReolStatisticsMonth $to);

  /**
   * Reset statistics.
   */
  //public function reset();

}
