<?php
/**
 * @file
 * Code for the eReolen help feature module.
 */

include_once 'reol_help.features.inc';

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_help_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view faq page',
    ),
    'authenticated user' => array(
      'view faq page',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_page_alter().
 *
 * Redirect FAQ node view pages to the faq page with right hash.
 */
function reol_help_page_alter(&$page) {
  $node = menu_get_object('node');
  if ($node && $node->type == 'faq' && arg(0) == 'node' && !arg(2)) {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $category_tid = $node_wrapper->field_category->value()->tid;
    // FAQ generates id in the following format:
    // t[tid]n[nid] where tid is the category term id and
    // nid is the FAQ node id. Redirect to show this one.
    drupal_goto('faq-page', array(
      'fragment' => 'category-' . $category_tid . ':answer-' . $node->nid,
    ));
  }
}

/**
 * Implements hook_preprocess_faq_category_questions_top_answers().
 *
 * Code borrowed from contrib/faq/includes/faq.questions_top.inc
 *
 * @see template_preprocess_faq_category_questions_top_answers()
 */
function reol_help_preprocess_faq_category_questions_top_answers(&$variables) {
  $data = $variables['data'];
  $category_display = $variables['category_display'];
  $term = $variables['term'];

  // Fetch configuration.
  $teaser = variable_get('faq_use_teaser', FALSE);
  $links = variable_get('faq_show_node_links', FALSE);

  $this_page = $_GET['q'];

  // Configure "back to top" link.
  $back_to_top = faq_init_back_to_top($this_page);

  $nodes = array();
  foreach ($data as $node) {
    $node_var = array();
    $anchor = 't' . $term->tid . 'n' . $node->nid;
    faq_view_question($node_var, $node, NULL, $anchor);
    faq_view_answer($node_var, $node, $back_to_top, $teaser, $links);

    // Added.
    $node_var['nid'] = $node->nid;
    $node_var['question'] = $node->title;

    $nodes[] = $node_var;
  }
  $variables['nodes'] = $nodes;
}
