<?php

include_once 'reol_help.features.inc';
/**
 * @file
 * Code for the eReolen help feature.
 */

/**
 * Implements hook_secure_permissions().
 *
 * Define which users should be able to perform a loan.
 */
function reol_help_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view faq page',
    ),
    'authenticated user' => array(
      'view faq page',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_page_alter().
 *
 * Redirect FAQ node view pages to the faq page with right hash.
 */
function reol_help_page_alter(&$page) {
  $node = menu_get_object('node');
  if ($node && $node->type == 'faq' && arg(0) == 'node' && !arg(2)) {
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $category_tid = $node_wrapper->field_category->value()->tid;
    // FAQ generates id in the following format:
    // t[tid]n[nid] where tid is the category term id and
    // nid is the FAQ node id. Redirect to show this one.
    drupal_goto('faq-page', array(
      'fragment' => 't' . $category_tid . 'n' . $node->nid,
    ));
  }
}
