<?php

/**
 * @file
 * Renders a text field as a ting carousel.
 */

/**
 * Implements hook_field_formatter_info().
 */
function reol_field_carousel_field_formatter_info() {
  return array(
    'reol_field_carousel' => array(
      'label' => t('Search carousel'),
      'description' => t('Displays the search strings as carousels.'),
      'field types' => array('text_long'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function reol_field_carousel_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'reol_field_carousel':
      foreach ($items as $item) {
        $tabs = array();
        $chunk = ting_search_carousel_get_covers($item['value'], 0, TING_SEARCH_CAROUSEL_CHUNK_SIZE);
        $tabs[] = array(
          // 'title' => $search['title'],
          // 'subtitle' => $search['subtitle'],
          // 'path' => 'ting_search_carousel/results/ajax/' . $index,
          'content' => $chunk['collections'], // $content,
          // 'offset' => -1, // $chunk['next_offset'],
        );
        $element[] = array(
          '#markup' => '<pre>' . $item['value'] . '</pre>',
          '#markup' => theme('ting_search_carousel', array('tabs' => $tabs, 'tab_position' => 'bottom')),
        );
      }
      break;
  }

  return $element;
}
