<?php

/**
 * @file
 * Extra additions for material_carousel for bReol.
 */

/**
 * Implements hook_preprocess_entity().
 */
function breol_carousel_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'material_carousel') {
      $wrapper = $variables['paragraphs_item']->wrapper();

      $color = $wrapper->field_material_carousel_color->value();
      if (isset($color['rgb'])) {
        $variables['classes_array'][] = 'material-carousel-colored';
        $variables['classes_array'][] = 'ding-carousel__wrapper';
        $variables['attributes_array']['style'] = 'background-color: ' . $color['rgb'] . ';';

        // We're only interested in rendering the carousel.
        $variables['content'] = $variables['content']['field_carousel'];
      }
    }
  }
}
