<?php

/**
 * @file
 * Code for the eReolen article feature.
 */

include_once 'ereol_article.features.inc';

/**
 * Implements hook_preprocess_node().
 */
function ereol_article_preprocess_node(&$variables) {
  $node = $variables['node'];
  $node_wrapper = entity_metadata_wrapper('node', $node);

  // Add background image on teaser for article.
  if ($node->type == 'article' && ($variables['view_mode'] == 'teaser' || $variables['view_mode'] == 'search_result')) {

    // Get image info.
    $image_field = $node_wrapper->field_ding_news_list_image->value();
    $image_uri = $image_field['uri'];

    // If stage_file proxy is enabled, give it a chance to download the file.
    if (function_exists('stage_file_proxy_process_file_uri')) {
      stage_file_proxy_process_file_uri($image_uri);
    }

    $image_for_sizing = image_style_path('reol_article_teaser_background', $image_uri);
    // Make sure image has been generated.
    if (!file_exists($image_for_sizing)) {
      image_style_create_derivative(image_style_load('reol_article_teaser_background'), $image_uri, $image_for_sizing);
    }

    list($image_w, $image_h) = getimagesize($image_for_sizing);

    // Add image style image.
    $params = array(
      'style_name' => 'reol_article_teaser_background',
      'path' => $image_uri,
      'getsize' => TRUE,
      'attributes' => array(
        'width' => $image_w,
        'height' => $image_h,
      ),
    );
    $variables['image_background'] = theme('image_style', $params);

    // Change text for read more link.
    $variables['readmore_text'] = t('Read entire article');
    $uri = entity_uri('node', $node);
    $variables['readmore'] = url($uri['path'], $uri['options']);
  }
}
