<?php
/**
 * @file
 * Inserts the DDB widget into selected pages.
 */

/**
 * Implements hook_menu().
 */
function ddb_widget_menu() {
  $items = array();

  $items['admin/config/user-interface/ddb_widget'] = array(
    'title' => 'DDB Widget',
    'description' => 'Administer DDB widget',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ddb_widget_settings_form'),
    'access arguments' => array('administer ddb'),
    'file' => 'includes/ddd_widget.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_proprocess_html().
 *
 * Checks if the JS code should inject the widget on the page. Mostly taken from
 * the core block module.
 */
function ddb_widget_preprocess_html(&$variables) {
  global $user;
  $config = variable_get('ddb_widget', []);

  // If a block has no roles associated, it is displayed for every role.
  // For blocks with roles associated, if none of the user's roles matches
  // the settings from this block, remove it from the block list.
  if (!empty(array_filter($config['role']['roles'])) && !array_intersect($config['role']['roles'], array_keys($user->roles))) {
    return;
  }

  // Limited visibility blocks must list at least one page.
  if ($config['path']['visibility'] == BLOCK_VISIBILITY_LISTED && empty($config['path']['pages'])) {
    return;
  }

  // Match path if necessary.
  if (!empty($config['path']['pages'])) {
    // Convert path to lowercase. This allows comparison of the same path
    // with different case. Ex: /Page, /page, /PAGE.
    $pages = drupal_strtolower($config['path']['pages']);
    if ($config['path']['visibility'] < BLOCK_VISIBILITY_PHP) {
      // Convert the Drupal path to lowercase.
      $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
      // Compare the lowercase internal and lowercase path alias (if any).
      $page_match = drupal_match_path($path, $pages);
      if ($path != $_GET['q']) {
        $page_match = $page_match || drupal_match_path($_GET['q'], $pages);
      }
      // When $block->visibility has a value of 0
      // (BLOCK_VISIBILITY_NOTLISTED), the block is displayed on all pages
      // except those listed in $block->pages. When set to 1
      // (BLOCK_VISIBILITY_LISTED), it is displayed only on those pages
      // listed in $block->pages.
      $page_match = !($config['path']['visibility'] xor $page_match);
    }
    else {
      $page_match = FALSE;
    }
  }
  else {
    $page_match = TRUE;
  }

  if (!$page_match) {
    return;
  }

  // All tests parsed, so lets inject the code.
  drupal_add_js($config['script']['code'], [
    'type' => 'inline',
    'scope' => 'footer',
  ]);
}
