<?php

/**
 * @file
 * Code for the Audio preview paragraph feature.
 */

include_once 'reol_audio_preview_paragraph.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function reol_audio_preview_paragraph_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'paragraphs_item') {
    if ($variables['paragraphs_item']->bundle() == 'audio_preview') {
      $ting_entity = NULL;

      $variables['cover'] =
        $variables['author'] =
        $variables['title'] = array();

      $wrapper = $variables['paragraphs_item']->wrapper();
      $link = $wrapper->field_preview_material->value();
      $ting_entity = _reol_base_object_from_url($link);

      if ($ting_entity) {
        drupal_add_js('https://play.pubhub.dk/1.1.4/js/player-kernel.min.js', 'external');
        drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/bowser/1.7.2/bowser.min.js', 'external');
        drupal_add_js(drupal_get_path('module', 'reol_audio_preview_paragraph') . '/js/audio_preview.js');

        $build = ting_object_view($ting_entity, 'compact');
        // For some reason this is an array.
        list($isbn,) = $ting_entity->getIsbn();
        list($author,) = $ting_entity->getCreators();
        $variables['isbn'] = $isbn;
        $variables['cover'] = $build['ting_cover'];
        $variables['author'] = check_plain($author);
        $variables['title'] = check_plain($ting_entity->getTitle());
      }
    }
  }
}
