<?php

/**
 * @file
 * Install, update and uninstall functions for the ereol_base module.
 */

/**
 * Enable ereol_inspiration.
 */
function ereol_base_update_7101() {
  module_enable(array('ereol_inspiration'), TRUE);
}

/**
 * Enable ereol_article, ereol_author_portrait, ereol_video.
 */
function ereol_base_update_7102() {
  module_enable(array('ereol_article', 'ereol_author_portrait', 'ereol_video'), TRUE);
}
